name: quickride
description: "A motorcycle ride-hailing app for Rwanda"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  app_settings: ^6.1.1
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  google_maps_flutter: ^2.12.1
  google_places_flutter: ^2.1.0
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  toastification: ^3.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/colored_logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
